export const portalCopy = {
  en: {
    // Nav
    navHome: 'Home',
    navSpeed: 'Speed',
    navBilling: 'Billing',
    navAlerts: 'Alerts',
    navSupport: 'Support',
    navStatus: 'Service status',
    navWifi: 'Wi-Fi configuration',
    navMenu: 'Menu',
    navNetwork: 'Network',
    customerPortal: 'Customer Portal',
    accountNumber: 'Account #849201',

    // Shared
    dashboard: 'Dashboard',
    account: 'Account',
    settings: 'Settings',
    online: 'Online',
    manage: 'Manage',
    saveChanges: 'Save changes',
    changesSaved: 'Changes saved',
    advancedSettings: 'Advanced settings',
    download: 'Download',
    upload: 'Upload',
    latency: 'Latency',
    mbps: 'Mbps',
    ms: 'ms',

    // Home
    portalHomeTitle: 'NetSurf ISP - Customer Portal',
    goodAfternoon: 'Good afternoon, Alex',
    homeSubtitleMobile: 'Sofia, Mladost 4 · Account #849201',
    homeSubtitleDesktop: 'Your fiber service is online and performing within plan.',
    fiberOnline: 'Ultra Fiber 1Gbps · Online',
    dueInDays: 'Due in 6 days · 18 Nov',
    planName: 'GigaHome + 180 TV Channels',
    planMeta: '34.90 BGN/mo · Optical FTTH Terminal Active',
    dataUsage: 'Data Usage',
    dataUsageValue: '420 GB / Unlimited',
    payBill: 'Pay Bill (34.90 BGN)',
    quickActions: 'Quick Actions',
    actionSpeedTitle: 'Test Wi-Fi Speed',
    actionSpeedSub: 'Run speed test',
    actionRebootTitle: 'Reboot Optical ONT',
    actionRebootSub: 'Restart terminal',
    actionTvTitle: 'TV Channels Guide',
    actionTvSub: '180 interactive',
    actionSupportTitle: 'Support Chat',
    actionSupportSub: '24/7 Sofia NOC',
    devicesConnected: '8 Devices Connected',
    meshActive: 'Wi-Fi 6 Mesh Network active',
    accountSettings: 'Account settings',

    // Speed
    speedTitle: 'NetSurf - Wi-Fi Speed Test',
    speedPageTitle: 'Wi-Fi Speed Test',
    connectedTo: 'Connected to NetSurf_5G_Home',
    livingRoomNode: 'Living Room Node',
    stableFiber: 'Stable Fiber',
    mbpsDownload: 'Mbps Download',
    ultraFast: 'Ultra Fast',
    pingLatency: 'Ping / Latency',
    jitter: 'Jitter',
    runSpeedTest: 'Run New Speed Test',
    testingFiber: 'Testing Fiber Stream...',
    signalStrength: 'Signal Strength',
    optimal: 'Optimal',
    signalDetail: 'Excellent (-48 dBm) • 5 of 5 Bars',
    connectedDevices: 'Connected Devices',
    devicesActive: '14 Active on Current Node',
    deviceTvs: '2 TVs',
    devicePhones: '4 Phones',
    deviceConsole: '1 Console',
    deviceIot: '7 IoT',
    performanceTip: 'Performance Tip',
    performanceTipBody:
      'Keep your optical router elevated off the floor and away from thick concrete walls for full home coverage.',

    // Billing
    billingTitle: 'NetSurf - Billing & Payments',
    billingHeading: 'Billing & Payments',
    billingSubtitle: 'Sofia • High-Speed Fiber',
    billingAccount: 'Account #BG-402981-SF',
    activeService: 'Active Service',
    currentBalance: 'Current Balance Due',
    upcomingCycle: 'Upcoming Cycle',
    inclVat: '(incl. 20% VAT)',
    dueOn: 'Due on November 24, 2024',
    payNowAmount: 'Pay 34.90 лв. Now',
    securePay: 'Instant card processing via Borica 3D Secure',
    autoPayEnabled: 'Auto-Pay: Enabled',
    autoPayDisabled: 'Auto-Pay: Disabled',
    autoPayHint: 'Debits automatically on the 24th',
    changeCard: 'Change card',
    expires: 'Expires 09/27',
    planAddons: 'Plan & Active Add-ons',
    planPeriod: 'Nov 1 – Nov 30',
    fiberPlan: 'Fiber 1000 Mbps Internet',
    fiberPlanSub: 'Symmetrical Gigabit Connection • Static IPv4',
    tvPlan: 'NetSurf Max TV',
    tvPlanSub: '180 channels + Diema Extra HD Package',
    monthlyTotal: 'Monthly Recurring Total',
    paymentHistory: 'Payment History',
    pdfInvoices: 'PDF Invoices',
    paidAutoPay: 'Paid via Auto-Pay',
    paidApplePay: 'Paid via Apple Pay',
    paidCard: 'Paid via Card',
    settled: 'Settled',
    taxDetails: 'Tax Details (ЕИК)',
    usageArchive: 'Usage Archive',

    // Alerts
    alertsTitle: 'NetSurf - Notifications & Preferences',
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    allAlerts: 'All Alerts',
    preferences: 'Preferences',
    recentAlerts: 'Recent Alerts',
    sofiaEastLive: 'Sofia East Node: Live',
    alertMaintTitle: 'Scheduled Maintenance Complete',
    alertMaintTime: '2h ago',
    alertMaintBody:
      'Mladost 4 node fiber upgrade finished at 04:30 AM. Speeds restored to 1 Gbps.',
    verifiedStable: 'Verified Stable',
    alertInvoiceTitle: 'Invoice Generated for November',
    alertInvoiceTime: 'Yesterday',
    alertInvoiceBody: 'Monthly invoice #NET-849201 is ready. Amount: 34.90 лв.',
    payNow: 'Pay Now',
    viewPdf: 'View PDF',
    alertWifiTitle: 'Wi-Fi Signal Optimization',
    alertWifiTime: '3 days ago',
    alertWifiBody:
      'Your router detected channel interference and auto-switched to channel 48 for lower latency.',
    viewLiveStatus: 'View live service status',
    notifPrefs: 'Notification Preferences',
    prefNetwork: 'Network & Outage Alerts',
    prefNetworkSub: 'Critical service interruptions and repair updates',
    prefBilling: 'Payment & Billing Reminders',
    prefBillingSub: 'Invoices and auto-pay receipts',
    prefOffers: 'Special Offers & Upgrades',
    prefOffersSub: 'New speed tiers, partner TV channels',
    needSms: 'Need SMS dispatch notifications?',

    // Support
    supportTitle: 'NetSurf - Support & Help',
    supportPageTitle: 'Support & Help',
    supportSubtitle: 'Sofia, Mladost 4 (Online)',
    ticketAssigned: 'Assigned',
    ticketTitle: 'Wi-Fi 6 Router Upgrade Request',
    ticketBody: 'Field technician scheduled for optical gateway deployment & testing.',
    trackStatus: 'Track status',
    hardwareDiag: 'Hardware Diagnostics',
    autoChecked: 'Auto-checked 2m ago',
    fiberOnt: 'Fiber ONT',
    syncedDbm: 'Synced (-18.2 dBm)',
    gatewayPing: 'Gateway Ping',
    packetLossZero: '0% Packet Loss',
    runTroubleshoot: 'Run Auto-Troubleshoot',
    directChannels: 'Direct Channels',
    liveChat: 'Live Chat',
    liveChatSub: 'Bulgarian & English support',
    waitTime: '~2 min wait',
    startChat: 'Start Chat',
    tollFree: '24/7 Toll-free',
    nationalDispatch: 'Bulgaria ISP National Dispatch',
    call: 'Call',
    fieldTech: 'Field Technician',
    fieldTechSub: 'Fiber splicing & in-home check',
    bookSlot: 'Book Slot',
    branchName: 'Mladost 4 Branch',
    untilClose: 'Until 20:00',
    branchSub: 'Al. Malinov Blvd 78 • 1.2 km',
    map: 'Map',
    knowledgeBase: 'Knowledge Base',
    guidesCount: '4 Guides',
    guideWifiTitle: 'Wi-Fi & Home Network',
    guideWifiSub: '5GHz setup, channel tips',
    guideWifiBody1:
      'Keep your NetSurf Dual-Band router at least 1 meter above floor level and away from thick concrete walls.',
    guideWifiBody2:
      'Connect Smart TVs and streaming consoles to NetSurf_5G_Home for gigabit throughput.',
    guideBillingTitle: 'Billing & EasyPay Codes',
    guideBillingSub: 'Grace period, client codes',
    guideBillingBody:
      'Invoices are generated on the 1st with payment grace period until the 25th. Pay at any EasyPay desk using subscriber code #8821940.',
    guideTvTitle: '4K TV Box & EPG Guide',
    guideTvSub: 'Stream reload, channel pairing',
    guideTvBody:
      'To clear the 4K IPTV stream cache, turn off the decoder power switch for 10 seconds, then reconnect via LAN port 2 on your optical gateway.',
    guideFiberTitle: 'Fiber Cable & LOS Warning',
    guideFiberSub: 'Yellow optical patch care',
    guideFiberBody:
      'Do not sharply bend the yellow optical patch cord. If the LOS indicator blinks red, the optical laser connection requires field inspection.',
    telemetryNote: 'Mladost 4 fiber node telemetry active. Peak network traffic normal.',

    // Status
    statusTitle: 'NetSurf - Service Health & Status',
    statusPageTitle: 'Service Status',
    serviceLocation: 'Service Location',
    serviceAddress: 'Sofia, Mladost 4, bl. 412',
    nodeLabel: 'Node:',
    nodeName: 'Sofia-East Optical Hub #12',
    synced: 'Synced',
    allSystemsOk: 'All Systems Operational',
    noIncidents:
      'No incidents or slowdowns detected in your district. Optical telemetry reporting optimal throughput.',
    packetLoss: 'Packet Loss',
    uptime: 'Uptime',
    districtGrid: 'District Network Grid',
    metroRing: 'Metropolitan Sofia Optical Ring',
    liveTelemetry: 'Live Telemetry',
    youHere: 'Mladost 4 (You)',
    allHubsNormal: 'All 8 Sofia Hubs Normal',
    yourGateway: 'Your Gateway',
    networkLogs: 'Network Logs & Upgrades',
    zeroOutages: '0 Active Outages',
    normal: 'Normal',
    scheduledMaint: 'Scheduled Maintenance',
    planned: 'Planned',
    maintWindow: 'Nov 28, 02:00 – 04:30 AM (EET)',
    maintBody:
      'Optical backbone routine maintenance. Expected brief connection downtime: < 15 mins for Mladost sector.',
    localSlowness: 'Experiencing Local Slowness?',
    localSlownessSub: 'Test your terminal or flag an unlisted hardware disruption.',
    runDiagnostics: 'Run Diagnostics',
    reportIssue: 'Report Local Issue',

    // Account
    accountTitle: 'NetSurf - Account & Settings',
    accountSubtitle: 'Profile & preferences',
    clientHash: 'Client #',
    fullName: 'Full name',
    serviceAddressLabel: 'Service address',
    phoneLabel: 'Phone',
    clientNumber: 'Client number',
    emailLabel: 'Email',
    changeEmail: 'Change email',
    changePassword: 'Change password',
    notifPreferences: 'Notification preferences',
    logOut: 'Log out',

    // Wi-Fi config
    wifiTitle: 'NetSurf - Wi-Fi Configuration',
    wifiPageTitle: 'Wi-Fi Configuration',
    wifiIntro: 'Change your home Wi-Fi name, password, and band. Changes apply after you save.',
    networkIdentity: 'Network identity',
    networkName: 'Network name (SSID)',
    networkNamePlaceholder: 'Network name',
    password: 'Password',
    wifiPasswordPlaceholder: 'Wi-Fi password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    radio: 'Radio',
    band: 'Band',
    securityType: 'Security type',
    wpa3Recommended: 'WPA3 (recommended)',
    visibilityPower: 'Visibility & power',
    hiddenNetwork: 'Hidden network',
    hiddenNetworkSub: 'Do not broadcast the network name (SSID)',
    wifiActive: 'Wi-Fi network active',
    wifiActiveSub: 'Turn the wireless radio on or off',
  },
  bg: {
    navHome: 'Начало',
    navSpeed: 'Скорост',
    navBilling: 'Плащания',
    navAlerts: 'Известия',
    navSupport: 'Поддръжка',
    navStatus: 'Статус на услугата',
    navWifi: 'Wi-Fi настройки',
    navMenu: 'Меню',
    navNetwork: 'Мрежа',
    customerPortal: 'Клиентски портал',
    accountNumber: 'Клиент №849201',

    dashboard: 'Табло',
    account: 'Акаунт',
    settings: 'Настройки',
    online: 'Онлайн',
    manage: 'Управление',
    saveChanges: 'Запази промените',
    changesSaved: 'Промените са запазени',
    advancedSettings: 'Разширени настройки',
    download: 'Сваляне',
    upload: 'Качване',
    latency: 'Латентност',
    mbps: 'Mbps',
    ms: 'ms',

    portalHomeTitle: 'NetSurf ISP - Клиентски портал',
    goodAfternoon: 'Добър ден, Алекс',
    homeSubtitleMobile: 'София, Младост 4 · Клиент №849201',
    homeSubtitleDesktop: 'Оптичната ви услуга е онлайн и работи в рамките на плана.',
    fiberOnline: 'Ultra Fiber 1Gbps · Онлайн',
    dueInDays: 'Дължимо след 6 дни · 18 ное',
    planName: 'GigaHome + 180 ТВ канала',
    planMeta: '34.90 лв./мес · Оптичен FTTH терминал активен',
    dataUsage: 'Използвани данни',
    dataUsageValue: '420 GB / Неограничено',
    payBill: 'Плати сметка (34.90 лв.)',
    quickActions: 'Бързи действия',
    actionSpeedTitle: 'Тест на Wi-Fi скорост',
    actionSpeedSub: 'Стартирай тест',
    actionRebootTitle: 'Рестарт на оптичен ONT',
    actionRebootSub: 'Рестартирай терминала',
    actionTvTitle: 'ТВ програма',
    actionTvSub: '180 интерактивни',
    actionSupportTitle: 'Чат с поддръжка',
    actionSupportSub: 'NOC София 24/7',
    devicesConnected: '8 свързани устройства',
    meshActive: 'Wi-Fi 6 Mesh мрежа активна',
    accountSettings: 'Настройки на акаунта',

    speedTitle: 'NetSurf - Тест на Wi-Fi скорост',
    speedPageTitle: 'Тест на Wi-Fi скорост',
    connectedTo: 'Свързан към NetSurf_5G_Home',
    livingRoomNode: 'Нода всекидневна',
    stableFiber: 'Стабилна оптика',
    mbpsDownload: 'Mbps сваляне',
    ultraFast: 'Ултра бързо',
    pingLatency: 'Пинг / латентност',
    jitter: 'Джитер',
    runSpeedTest: 'Нов тест на скоростта',
    testingFiber: 'Тестване на оптичния поток...',
    signalStrength: 'Сила на сигнала',
    optimal: 'Оптимален',
    signalDetail: 'Отличен (-48 dBm) • 5 от 5 деления',
    connectedDevices: 'Свързани устройства',
    devicesActive: '14 активни на текущата нода',
    deviceTvs: '2 ТВ',
    devicePhones: '4 телефона',
    deviceConsole: '1 конзола',
    deviceIot: '7 IoT',
    performanceTip: 'Съвет за производителност',
    performanceTipBody:
      'Дръжте оптичния рутер повдигнат от пода и далеч от дебели бетонни стени за пълно покритие.',

    billingTitle: 'NetSurf - Плащания и фактури',
    billingHeading: 'Плащания и фактури',
    billingSubtitle: 'София • Високоскоростна оптика',
    billingAccount: 'Клиент №BG-402981-SF',
    activeService: 'Активна услуга',
    currentBalance: 'Текущо дължимо',
    upcomingCycle: 'Предстоящ цикъл',
    inclVat: '(с включен 20% ДДС)',
    dueOn: 'Падеж на 24 ноември 2024',
    payNowAmount: 'Плати 34.90 лв. сега',
    securePay: 'Моментална обработка чрез Борика 3D Secure',
    autoPayEnabled: 'Автоплащане: Включено',
    autoPayDisabled: 'Автоплащане: Изключено',
    autoPayHint: 'Тегли се автоматично на 24-то число',
    changeCard: 'Смени карта',
    expires: 'Валидна до 09/27',
    planAddons: 'План и активни добавки',
    planPeriod: '1 ное – 30 ное',
    fiberPlan: 'Оптика Fiber 1000 Mbps',
    fiberPlanSub: 'Симетрична гигабитова връзка • Статичен IPv4',
    tvPlan: 'NetSurf Max TV',
    tvPlanSub: '180 канала + Diema Extra HD пакет',
    monthlyTotal: 'Месечна сума',
    paymentHistory: 'История на плащанията',
    pdfInvoices: 'PDF фактури',
    paidAutoPay: 'Платено с автоплащане',
    paidApplePay: 'Платено с Apple Pay',
    paidCard: 'Платено с карта',
    settled: 'Уредено',
    taxDetails: 'Данъчни данни (ЕИК)',
    usageArchive: 'Архив на потребление',

    alertsTitle: 'NetSurf - Известия и предпочитания',
    notifications: 'Известия',
    markAllRead: 'Маркирай всички',
    allAlerts: 'Всички известия',
    preferences: 'Предпочитания',
    recentAlerts: 'Последни известия',
    sofiaEastLive: 'София Изток: На живо',
    alertMaintTitle: 'Планираната поддръжка приключи',
    alertMaintTime: 'преди 2ч',
    alertMaintBody:
      'Ъпгрейдът на нодата в Младост 4 приключи в 04:30. Скоростите са възстановени до 1 Gbps.',
    verifiedStable: 'Потвърдено стабилно',
    alertInvoiceTitle: 'Фактура за ноември е готова',
    alertInvoiceTime: 'Вчера',
    alertInvoiceBody: 'Месечна фактура #NET-849201 е готова. Сума: 34.90 лв.',
    payNow: 'Плати сега',
    viewPdf: 'Виж PDF',
    alertWifiTitle: 'Оптимизация на Wi-Fi сигнала',
    alertWifiTime: 'преди 3 дни',
    alertWifiBody:
      'Рутерът откри смущения и автоматично превключи на канал 48 за по-ниска латентност.',
    viewLiveStatus: 'Виж статус на услугата на живо',
    notifPrefs: 'Предпочитания за известия',
    prefNetwork: 'Мрежа и прекъсвания',
    prefNetworkSub: 'Критични прекъсвания и ремонтни обновления',
    prefBilling: 'Плащания и фактури',
    prefBillingSub: 'Фактури и разписки за автоплащане',
    prefOffers: 'Оферти и ъпгрейди',
    prefOffersSub: 'Нови скорости и партньорски ТВ канали',
    needSms: 'Нужни са SMS известия?',

    supportTitle: 'NetSurf - Поддръжка и помощ',
    supportPageTitle: 'Поддръжка и помощ',
    supportSubtitle: 'София, Младост 4 (Онлайн)',
    ticketAssigned: 'Назначен',
    ticketTitle: 'Заявка за ъпгрейд на Wi-Fi 6 рутер',
    ticketBody: 'Планиран е техник за инсталация и тест на оптичния гейтуей.',
    trackStatus: 'Проследи статус',
    hardwareDiag: 'Хардуерна диагностика',
    autoChecked: 'Автопроверка преди 2 мин',
    fiberOnt: 'Оптичен ONT',
    syncedDbm: 'Синхронизиран (-18.2 dBm)',
    gatewayPing: 'Пинг към гейтуей',
    packetLossZero: '0% загуба на пакети',
    runTroubleshoot: 'Автоматична диагностика',
    directChannels: 'Директни канали',
    liveChat: 'Чат на живо',
    liveChatSub: 'Поддръжка на български и английски',
    waitTime: '~2 мин чакане',
    startChat: 'Започни чат',
    tollFree: '24/7 безплатен',
    nationalDispatch: 'Национален диспечер NetSurf',
    call: 'Обади се',
    fieldTech: 'Теренен техник',
    fieldTechSub: 'Сплайсиране и проверка в дома',
    bookSlot: 'Запази час',
    branchName: 'Клон Младост 4',
    untilClose: 'До 20:00',
    branchSub: 'бул. Ал. Малинов 78 • 1.2 км',
    map: 'Карта',
    knowledgeBase: 'База знания',
    guidesCount: '4 ръководства',
    guideWifiTitle: 'Wi-Fi и домашна мрежа',
    guideWifiSub: '5GHz настройка, канали',
    guideWifiBody1:
      'Дръжте двулентовия NetSurf рутер поне 1 метър над пода и далеч от дебели бетонни стени.',
    guideWifiBody2:
      'Свържете Smart TV и конзоли към NetSurf_5G_Home за гигабитова скорост.',
    guideBillingTitle: 'Плащания и EasyPay кодове',
    guideBillingSub: 'Гратисен период, клиентски кодове',
    guideBillingBody:
      'Фактурите се издават на 1-во число с гратисен период до 25-то. Плащайте на EasyPay с код #8821940.',
    guideTvTitle: '4K ТВ бокс и EPG',
    guideTvSub: 'Презареждане на поток, канали',
    guideTvBody:
      'За изчистване на 4K IPTV кеша изключете декодера за 10 секунди, после свържете през LAN порт 2 на оптичния гейтуей.',
    guideFiberTitle: 'Оптичен кабел и LOS предупреждение',
    guideFiberSub: 'Грижа за жълтия пачкорд',
    guideFiberBody:
      'Не прегъвайте рязко жълтия оптичен пачкорд. Ако LOS индикаторът мига в червено, връзката се нуждае от теренна проверка.',
    telemetryNote: 'Телеметрията на нодата в Младост 4 е активна. Пиковият трафик е нормален.',

    statusTitle: 'NetSurf - Здраве и статус на услугата',
    statusPageTitle: 'Статус на услугата',
    serviceLocation: 'Локация на услугата',
    serviceAddress: 'София, Младост 4, бл. 412',
    nodeLabel: 'Нода:',
    nodeName: 'София-Изток оптичен хъб #12',
    synced: 'Синхронизирано',
    allSystemsOk: 'Всички системи работят',
    noIncidents:
      'Няма инциденти или забавяния във вашия район. Оптичната телеметрия показва оптимален поток.',
    packetLoss: 'Загуба на пакети',
    uptime: 'Uptime',
    districtGrid: 'Районна мрежова мрежа',
    metroRing: 'Метрополитен оптичен пръстен София',
    liveTelemetry: 'Жива телеметрия',
    youHere: 'Младост 4 (Вие)',
    allHubsNormal: 'Всички 8 хъба в София са нормални',
    yourGateway: 'Вашият гейтуей',
    networkLogs: 'Мрежови логове и ъпгрейди',
    zeroOutages: '0 активни прекъсвания',
    normal: 'Нормално',
    scheduledMaint: 'Планирана поддръжка',
    planned: 'Планирано',
    maintWindow: '28 ное, 02:00 – 04:30 (EET)',
    maintBody:
      'Рутинна поддръжка на оптичния гръбнак. Очаквано кратко прекъсване: < 15 мин за сектор Младост.',
    localSlowness: 'Локално забавяне?',
    localSlownessSub: 'Тествайте терминала или докладвайте нерегистриран хардуерен проблем.',
    runDiagnostics: 'Стартирай диагностика',
    reportIssue: 'Докладвай проблем',

    accountTitle: 'NetSurf - Акаунт и настройки',
    accountSubtitle: 'Профил и предпочитания',
    clientHash: 'Клиент №',
    fullName: 'Пълно име',
    serviceAddressLabel: 'Адрес на услугата',
    phoneLabel: 'Телефон',
    clientNumber: 'Клиентски номер',
    emailLabel: 'Имейл',
    changeEmail: 'Смени имейл',
    changePassword: 'Смени парола',
    notifPreferences: 'Предпочитания за известия',
    logOut: 'Изход',

    wifiTitle: 'NetSurf - Wi-Fi настройки',
    wifiPageTitle: 'Wi-Fi настройки',
    wifiIntro: 'Променете името, паролата и лентата на домашния Wi-Fi. Промените важат след запазване.',
    networkIdentity: 'Идентичност на мрежата',
    networkName: 'Име на мрежата (SSID)',
    networkNamePlaceholder: 'Име на мрежата',
    password: 'Парола',
    wifiPasswordPlaceholder: 'Wi-Fi парола',
    showPassword: 'Покажи парола',
    hidePassword: 'Скрий парола',
    radio: 'Радио',
    band: 'Лента',
    securityType: 'Тип сигурност',
    wpa3Recommended: 'WPA3 (препоръчан)',
    visibilityPower: 'Видимост и захранване',
    hiddenNetwork: 'Скрита мрежа',
    hiddenNetworkSub: 'Не излъчвай името на мрежата (SSID)',
    wifiActive: 'Wi-Fi мрежата е активна',
    wifiActiveSub: 'Включи или изключи безжичното радио',
  },
} as const;

export type PortalCopy = (typeof portalCopy)['en'];
export type PortalCopyKey = keyof PortalCopy;
